# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ava's ACA Experience!
email: avaeelerog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! I will be posting about my
  experiences with Austin Coding Academy and I hope you enjoy!
baseurl: "/aca-blog" # the subpath of your site, e.g. /blog
url: "http://avagore.github.io" # the base hostname & protocol for your site
twitter_username: miss_gore21
github_username:  avagore

# Build settings
markdown: kramdown
